#!/bin/bash
# Generated by Arch-Base TUI Configuration Wizard (Prototype)

# System Configuration
HOSTNAME="arch-desktop"
TIMEZONE="America/New_York"
LOCALE="en_US.UTF-8"
KEYMAP="us"

# User Configuration  
USERNAME="damien"
USER_GROUPS="wheel,audio,video,storage"

# Disk Configuration
TARGET_DISK="/dev/nvme0n1"
EFI_SIZE="512M"
CRYPTROOT_NAME="cryptroot"
FS_TYPE="btrfs"
BTRFS_SUBVOLUME_LAYOUT="default"
COMPRESS_TYPE="zstd"
SWAPFILE_ENABLED="true"
SWAPFILE_SIZE_MB="4096"

# Package Configuration
INSTALL_MODE="standard"
ESSENTIAL_PACKAGES="plasma-meta konsole dolphin firefox"

# Installation Behavior
AUTO_REBOOT="false"
SKIP_NON_FREE="false"
